/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibApi;

import ChronoSheetsClient.ApiException;
import ChronoSheetsClientLibModel.CSApiResponseBoolean;
import ChronoSheetsClientLibModel.CSApiResponseForPaginatedListTimesheetFileAttachment;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FileAttachmentsApi
 */
@Ignore
public class FileAttachmentsApiTest {

    private final FileAttachmentsApi api = new FileAttachmentsApi();

    
    /**
     * Delete a particular timesheet file attachment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fileAttachmentsDeleteTimesheetFileAttachmentTest() throws ApiException {
        Integer fileAttachmentId = null;
        String xChronosheetsAuth = null;
        CSApiResponseBoolean response = api.fileAttachmentsDeleteTimesheetFileAttachment(fileAttachmentId, xChronosheetsAuth);

        // TODO: test validations
    }
    
    /**
     * Get my file attachments.  Get files you&#39;ve attached to timesheets.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fileAttachmentsGetMyFileAttachmentsTest() throws ApiException {
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        String xChronosheetsAuth = null;
        Integer skip = null;
        Integer take = null;
        CSApiResponseForPaginatedListTimesheetFileAttachment response = api.fileAttachmentsGetMyFileAttachments(startDate, endDate, xChronosheetsAuth, skip, take);

        // TODO: test validations
    }
    
}
