/*
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibApi;

import ChronoSheetsClient.ApiException;
import ChronoSheetsClientLibModel.CsApiApiResponseBoolean;
import ChronoSheetsClientLibModel.CsApiApiResponseInt32;
import ChronoSheetsClientLibModel.CsApiApiResponseListProject;
import ChronoSheetsClientLibModel.CsApiApiResponseProject;
import ChronoSheetsClientLibModel.CsApiInsertProjectRequest;
import ChronoSheetsClientLibModel.CsApiUpdateProjectRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectsApi
 */
@Ignore
public class ProjectsApiTest {

    private final ProjectsApi api = new ProjectsApi();

    
    /**
     * Create a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void projectsCreateProjectTest() throws ApiException {
        CsApiInsertProjectRequest request = null;
        String xChronosheetsAuth = null;
        CsApiApiResponseInt32 response = api.projectsCreateProject(request, xChronosheetsAuth);

        // TODO: test validations
    }
    
    /**
     * Get project by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void projectsGetProjectByIdTest() throws ApiException {
        Integer projectId = null;
        String xChronosheetsAuth = null;
        CsApiApiResponseProject response = api.projectsGetProjectById(projectId, xChronosheetsAuth);

        // TODO: test validations
    }
    
    /**
     * Get projects for a particular client
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void projectsGetProjectsForClientTest() throws ApiException {
        Integer clientId = null;
        String xChronosheetsAuth = null;
        CsApiApiResponseListProject response = api.projectsGetProjectsForClient(clientId, xChronosheetsAuth);

        // TODO: test validations
    }
    
    /**
     * Update a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void projectsUpdateProjectTest() throws ApiException {
        CsApiUpdateProjectRequest request = null;
        String xChronosheetsAuth = null;
        CsApiApiResponseBoolean response = api.projectsUpdateProject(request, xChronosheetsAuth);

        // TODO: test validations
    }
    
}
