/*
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibApi;

import ChronoSheetsClient.ApiException;
import ChronoSheetsClientLibModel.CSApiResponseInt32;
import ChronoSheetsClientLibModel.CSApiResponseListUserHourlyRate;
import ChronoSheetsClientLibModel.CSInsertUserHourlyRateRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserPayRatesApi
 */
@Ignore
public class UserPayRatesApiTest {

    private final UserPayRatesApi api = new UserPayRatesApi();

    
    /**
     * Create a new pay rate for a particular user, archiving the previous pay rate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userPayRatesCreatePayRateTest() throws ApiException {
        CSInsertUserHourlyRateRequest request = null;
        String xChronosheetsAuth = null;
        CSApiResponseInt32 response = api.userPayRatesCreatePayRate(request, xChronosheetsAuth);

        // TODO: test validations
    }
    
    /**
     * Get a collection of pay rates for a particular user, specified by user id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userPayRatesGetPayRatesTest() throws ApiException {
        Integer userId = null;
        String xChronosheetsAuth = null;
        CSApiResponseListUserHourlyRate response = api.userPayRatesGetPayRates(userId, xChronosheetsAuth);

        // TODO: test validations
    }
    
}
