/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibModel;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TimeSlot
 */
public class TimeSlotTest {
    private final TimeSlot model = new TimeSlot();

    /**
     * Model tests for TimeSlot
     */
    @Test
    public void testTimeSlot() {
        // TODO: test TimeSlot
    }

    /**
     * Test the property 'dayType'
     */
    @Test
    public void dayTypeTest() {
        // TODO: test dayType
    }

    /**
     * Test the property 'usualHourId'
     */
    @Test
    public void usualHourIdTest() {
        // TODO: test usualHourId
    }

    /**
     * Test the property 'startHour'
     */
    @Test
    public void startHourTest() {
        // TODO: test startHour
    }

    /**
     * Test the property 'startMinute'
     */
    @Test
    public void startMinuteTest() {
        // TODO: test startMinute
    }

    /**
     * Test the property 'endHour'
     */
    @Test
    public void endHourTest() {
        // TODO: test endHour
    }

    /**
     * Test the property 'endMinute'
     */
    @Test
    public void endMinuteTest() {
        // TODO: test endMinute
    }

    /**
     * Test the property 'isValid'
     */
    @Test
    public void isValidTest() {
        // TODO: test isValid
    }

}
