/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibModel;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateMyProfileRequest
 */
public class UpdateMyProfileRequestTest {
    private final UpdateMyProfileRequest model = new UpdateMyProfileRequest();

    /**
     * Model tests for UpdateMyProfileRequest
     */
    @Test
    public void testUpdateMyProfileRequest() {
        // TODO: test UpdateMyProfileRequest
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'oldPassword'
     */
    @Test
    public void oldPasswordTest() {
        // TODO: test oldPassword
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

    /**
     * Test the property 'confirmNewPassword'
     */
    @Test
    public void confirmNewPasswordTest() {
        // TODO: test confirmNewPassword
    }

    /**
     * Test the property 'isSubscribedToNewsletter'
     */
    @Test
    public void isSubscribedToNewsletterTest() {
        // TODO: test isSubscribedToNewsletter
    }

    /**
     * Test the property 'wantsToChangePassword'
     */
    @Test
    public void wantsToChangePasswordTest() {
        // TODO: test wantsToChangePassword
    }

}
