/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibModel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * CreateAutomationStepRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-03T19:40:40.863+10:00[Australia/Sydney]")
public class CreateAutomationStepRequest {
  public static final String SERIALIZED_NAME_GEOFENCING_ID = "GeofencingId";
  @SerializedName(SERIALIZED_NAME_GEOFENCING_ID)
  private Integer geofencingId;

  public static final String SERIALIZED_NAME_NFC_ID = "NfcId";
  @SerializedName(SERIALIZED_NAME_NFC_ID)
  private Integer nfcId;

  /**
   * Gets or Sets automationActionType
   */
  @JsonAdapter(AutomationActionTypeEnum.Adapter.class)
  public enum AutomationActionTypeEnum {
    ENTERGEOFENCE("EnterGeofence"),
    
    EXITGEOFENCE("ExitGeofence"),
    
    TAPONNFC("TapOnNfc");

    private String value;

    AutomationActionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AutomationActionTypeEnum fromValue(String value) {
      for (AutomationActionTypeEnum b : AutomationActionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AutomationActionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AutomationActionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AutomationActionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AutomationActionTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AUTOMATION_ACTION_TYPE = "AutomationActionType";
  @SerializedName(SERIALIZED_NAME_AUTOMATION_ACTION_TYPE)
  private AutomationActionTypeEnum automationActionType;

  public static final String SERIALIZED_NAME_LATITUDE = "Latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private Double latitude;

  public static final String SERIALIZED_NAME_LONGITUDE = "Longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private Double longitude;

  public static final String SERIALIZED_NAME_CLIENT_TIME = "ClientTime";
  @SerializedName(SERIALIZED_NAME_CLIENT_TIME)
  private OffsetDateTime clientTime;


  public CreateAutomationStepRequest geofencingId(Integer geofencingId) {
    
    this.geofencingId = geofencingId;
    return this;
  }

   /**
   * Get geofencingId
   * @return geofencingId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getGeofencingId() {
    return geofencingId;
  }


  public void setGeofencingId(Integer geofencingId) {
    this.geofencingId = geofencingId;
  }


  public CreateAutomationStepRequest nfcId(Integer nfcId) {
    
    this.nfcId = nfcId;
    return this;
  }

   /**
   * Get nfcId
   * @return nfcId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNfcId() {
    return nfcId;
  }


  public void setNfcId(Integer nfcId) {
    this.nfcId = nfcId;
  }


  public CreateAutomationStepRequest automationActionType(AutomationActionTypeEnum automationActionType) {
    
    this.automationActionType = automationActionType;
    return this;
  }

   /**
   * Get automationActionType
   * @return automationActionType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AutomationActionTypeEnum getAutomationActionType() {
    return automationActionType;
  }


  public void setAutomationActionType(AutomationActionTypeEnum automationActionType) {
    this.automationActionType = automationActionType;
  }


  public CreateAutomationStepRequest latitude(Double latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getLatitude() {
    return latitude;
  }


  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }


  public CreateAutomationStepRequest longitude(Double longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getLongitude() {
    return longitude;
  }


  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }


  public CreateAutomationStepRequest clientTime(OffsetDateTime clientTime) {
    
    this.clientTime = clientTime;
    return this;
  }

   /**
   * Get clientTime
   * @return clientTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getClientTime() {
    return clientTime;
  }


  public void setClientTime(OffsetDateTime clientTime) {
    this.clientTime = clientTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAutomationStepRequest createAutomationStepRequest = (CreateAutomationStepRequest) o;
    return Objects.equals(this.geofencingId, createAutomationStepRequest.geofencingId) &&
        Objects.equals(this.nfcId, createAutomationStepRequest.nfcId) &&
        Objects.equals(this.automationActionType, createAutomationStepRequest.automationActionType) &&
        Objects.equals(this.latitude, createAutomationStepRequest.latitude) &&
        Objects.equals(this.longitude, createAutomationStepRequest.longitude) &&
        Objects.equals(this.clientTime, createAutomationStepRequest.clientTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geofencingId, nfcId, automationActionType, latitude, longitude, clientTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAutomationStepRequest {\n");
    sb.append("    geofencingId: ").append(toIndentedString(geofencingId)).append("\n");
    sb.append("    nfcId: ").append(toIndentedString(nfcId)).append("\n");
    sb.append("    automationActionType: ").append(toIndentedString(automationActionType)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    clientTime: ").append(toIndentedString(clientTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

