/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibModel;

import java.util.Objects;
import java.util.Arrays;
import ChronoSheetsClientLibModel.CSBasicCoordinate;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A request object for creating a new geofence
 */
@ApiModel(description = "A request object for creating a new geofence")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-18T19:20:43.284+10:00")
public class CSCreateGeoFenceRequest {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("FenceCoordinates")
  private List<CSBasicCoordinate> fenceCoordinates = null;

  @SerializedName("TriggerJobCodeId")
  private Integer triggerJobCodeId = null;

  @SerializedName("TriggerTaskId")
  private Integer triggerTaskId = null;

  @SerializedName("SendAlertToOrgGroupId")
  private Integer sendAlertToOrgGroupId = null;

  /**
   * Define when you want the alerts to be setn
   */
  @JsonAdapter(AlertSettingsEnum.Adapter.class)
  public enum AlertSettingsEnum {
    NONE("None"),
    
    SENDWHENENTERING("SendWhenEntering"),
    
    SENDWHENEXITING("SendWhenExiting"),
    
    SENDWHENENTERINGOREXITING("SendWhenEnteringOrExiting");

    private String value;

    AlertSettingsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AlertSettingsEnum fromValue(String text) {
      for (AlertSettingsEnum b : AlertSettingsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AlertSettingsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AlertSettingsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AlertSettingsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AlertSettingsEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("AlertSettings")
  private AlertSettingsEnum alertSettings = null;

  /**
   * Define how to you want to trigger the timesheet automation
   */
  @JsonAdapter(TriggerSettingsEnum.Adapter.class)
  public enum TriggerSettingsEnum {
    NONE("None"),
    
    STARTTIMESHEETWHENENTERING("StartTimesheetWhenEntering"),
    
    STOPTIMESHEETWHENENTERING("StopTimesheetWhenEntering"),
    
    STARTONENTERSTOPONLEAVE("StartOnEnterStopOnLeave");

    private String value;

    TriggerSettingsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TriggerSettingsEnum fromValue(String text) {
      for (TriggerSettingsEnum b : TriggerSettingsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TriggerSettingsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TriggerSettingsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TriggerSettingsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TriggerSettingsEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("TriggerSettings")
  private TriggerSettingsEnum triggerSettings = null;

  @SerializedName("StartTimeHour")
  private Integer startTimeHour = null;

  @SerializedName("StartTimeMinute")
  private Integer startTimeMinute = null;

  @SerializedName("EndTimeHour")
  private Integer endTimeHour = null;

  @SerializedName("EndTimeMinute")
  private Integer endTimeMinute = null;

  public CSCreateGeoFenceRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the geo fence
   * @return name
  **/
  @ApiModelProperty(value = "The name of the geo fence")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CSCreateGeoFenceRequest fenceCoordinates(List<CSBasicCoordinate> fenceCoordinates) {
    this.fenceCoordinates = fenceCoordinates;
    return this;
  }

  public CSCreateGeoFenceRequest addFenceCoordinatesItem(CSBasicCoordinate fenceCoordinatesItem) {
    if (this.fenceCoordinates == null) {
      this.fenceCoordinates = new ArrayList<CSBasicCoordinate>();
    }
    this.fenceCoordinates.add(fenceCoordinatesItem);
    return this;
  }

   /**
   * A list of coordinates specifying the geofence region
   * @return fenceCoordinates
  **/
  @ApiModelProperty(value = "A list of coordinates specifying the geofence region")
  public List<CSBasicCoordinate> getFenceCoordinates() {
    return fenceCoordinates;
  }

  public void setFenceCoordinates(List<CSBasicCoordinate> fenceCoordinates) {
    this.fenceCoordinates = fenceCoordinates;
  }

  public CSCreateGeoFenceRequest triggerJobCodeId(Integer triggerJobCodeId) {
    this.triggerJobCodeId = triggerJobCodeId;
    return this;
  }

   /**
   * The job code to be used when the person enters/leaves the geofence
   * @return triggerJobCodeId
  **/
  @ApiModelProperty(value = "The job code to be used when the person enters/leaves the geofence")
  public Integer getTriggerJobCodeId() {
    return triggerJobCodeId;
  }

  public void setTriggerJobCodeId(Integer triggerJobCodeId) {
    this.triggerJobCodeId = triggerJobCodeId;
  }

  public CSCreateGeoFenceRequest triggerTaskId(Integer triggerTaskId) {
    this.triggerTaskId = triggerTaskId;
    return this;
  }

   /**
   * The task to be used when the person enters/leaves the geofence
   * @return triggerTaskId
  **/
  @ApiModelProperty(value = "The task to be used when the person enters/leaves the geofence")
  public Integer getTriggerTaskId() {
    return triggerTaskId;
  }

  public void setTriggerTaskId(Integer triggerTaskId) {
    this.triggerTaskId = triggerTaskId;
  }

  public CSCreateGeoFenceRequest sendAlertToOrgGroupId(Integer sendAlertToOrgGroupId) {
    this.sendAlertToOrgGroupId = sendAlertToOrgGroupId;
    return this;
  }

   /**
   * Send an alert to a user, specified by their user ID
   * @return sendAlertToOrgGroupId
  **/
  @ApiModelProperty(value = "Send an alert to a user, specified by their user ID")
  public Integer getSendAlertToOrgGroupId() {
    return sendAlertToOrgGroupId;
  }

  public void setSendAlertToOrgGroupId(Integer sendAlertToOrgGroupId) {
    this.sendAlertToOrgGroupId = sendAlertToOrgGroupId;
  }

  public CSCreateGeoFenceRequest alertSettings(AlertSettingsEnum alertSettings) {
    this.alertSettings = alertSettings;
    return this;
  }

   /**
   * Define when you want the alerts to be setn
   * @return alertSettings
  **/
  @ApiModelProperty(value = "Define when you want the alerts to be setn")
  public AlertSettingsEnum getAlertSettings() {
    return alertSettings;
  }

  public void setAlertSettings(AlertSettingsEnum alertSettings) {
    this.alertSettings = alertSettings;
  }

  public CSCreateGeoFenceRequest triggerSettings(TriggerSettingsEnum triggerSettings) {
    this.triggerSettings = triggerSettings;
    return this;
  }

   /**
   * Define how to you want to trigger the timesheet automation
   * @return triggerSettings
  **/
  @ApiModelProperty(value = "Define how to you want to trigger the timesheet automation")
  public TriggerSettingsEnum getTriggerSettings() {
    return triggerSettings;
  }

  public void setTriggerSettings(TriggerSettingsEnum triggerSettings) {
    this.triggerSettings = triggerSettings;
  }

  public CSCreateGeoFenceRequest startTimeHour(Integer startTimeHour) {
    this.startTimeHour = startTimeHour;
    return this;
  }

   /**
   * The start hour in which this geofence should apply.  After this time, the geofence will be active.
   * @return startTimeHour
  **/
  @ApiModelProperty(value = "The start hour in which this geofence should apply.  After this time, the geofence will be active.")
  public Integer getStartTimeHour() {
    return startTimeHour;
  }

  public void setStartTimeHour(Integer startTimeHour) {
    this.startTimeHour = startTimeHour;
  }

  public CSCreateGeoFenceRequest startTimeMinute(Integer startTimeMinute) {
    this.startTimeMinute = startTimeMinute;
    return this;
  }

   /**
   * The start minute in which this geofence should apply.  After this time, the geofence will be active.
   * @return startTimeMinute
  **/
  @ApiModelProperty(value = "The start minute in which this geofence should apply.  After this time, the geofence will be active.")
  public Integer getStartTimeMinute() {
    return startTimeMinute;
  }

  public void setStartTimeMinute(Integer startTimeMinute) {
    this.startTimeMinute = startTimeMinute;
  }

  public CSCreateGeoFenceRequest endTimeHour(Integer endTimeHour) {
    this.endTimeHour = endTimeHour;
    return this;
  }

   /**
   * The end hour in which this geofence will stop applying.  After this time, the geofence will be inactive.
   * @return endTimeHour
  **/
  @ApiModelProperty(value = "The end hour in which this geofence will stop applying.  After this time, the geofence will be inactive.")
  public Integer getEndTimeHour() {
    return endTimeHour;
  }

  public void setEndTimeHour(Integer endTimeHour) {
    this.endTimeHour = endTimeHour;
  }

  public CSCreateGeoFenceRequest endTimeMinute(Integer endTimeMinute) {
    this.endTimeMinute = endTimeMinute;
    return this;
  }

   /**
   * The end minute in which this geofence will stop applying.  After this time, the geofence will be inactive.
   * @return endTimeMinute
  **/
  @ApiModelProperty(value = "The end minute in which this geofence will stop applying.  After this time, the geofence will be inactive.")
  public Integer getEndTimeMinute() {
    return endTimeMinute;
  }

  public void setEndTimeMinute(Integer endTimeMinute) {
    this.endTimeMinute = endTimeMinute;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CSCreateGeoFenceRequest createGeoFenceRequest = (CSCreateGeoFenceRequest) o;
    return Objects.equals(this.name, createGeoFenceRequest.name) &&
        Objects.equals(this.fenceCoordinates, createGeoFenceRequest.fenceCoordinates) &&
        Objects.equals(this.triggerJobCodeId, createGeoFenceRequest.triggerJobCodeId) &&
        Objects.equals(this.triggerTaskId, createGeoFenceRequest.triggerTaskId) &&
        Objects.equals(this.sendAlertToOrgGroupId, createGeoFenceRequest.sendAlertToOrgGroupId) &&
        Objects.equals(this.alertSettings, createGeoFenceRequest.alertSettings) &&
        Objects.equals(this.triggerSettings, createGeoFenceRequest.triggerSettings) &&
        Objects.equals(this.startTimeHour, createGeoFenceRequest.startTimeHour) &&
        Objects.equals(this.startTimeMinute, createGeoFenceRequest.startTimeMinute) &&
        Objects.equals(this.endTimeHour, createGeoFenceRequest.endTimeHour) &&
        Objects.equals(this.endTimeMinute, createGeoFenceRequest.endTimeMinute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, fenceCoordinates, triggerJobCodeId, triggerTaskId, sendAlertToOrgGroupId, alertSettings, triggerSettings, startTimeHour, startTimeMinute, endTimeHour, endTimeMinute);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CSCreateGeoFenceRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fenceCoordinates: ").append(toIndentedString(fenceCoordinates)).append("\n");
    sb.append("    triggerJobCodeId: ").append(toIndentedString(triggerJobCodeId)).append("\n");
    sb.append("    triggerTaskId: ").append(toIndentedString(triggerTaskId)).append("\n");
    sb.append("    sendAlertToOrgGroupId: ").append(toIndentedString(sendAlertToOrgGroupId)).append("\n");
    sb.append("    alertSettings: ").append(toIndentedString(alertSettings)).append("\n");
    sb.append("    triggerSettings: ").append(toIndentedString(triggerSettings)).append("\n");
    sb.append("    startTimeHour: ").append(toIndentedString(startTimeHour)).append("\n");
    sb.append("    startTimeMinute: ").append(toIndentedString(startTimeMinute)).append("\n");
    sb.append("    endTimeHour: ").append(toIndentedString(endTimeHour)).append("\n");
    sb.append("    endTimeMinute: ").append(toIndentedString(endTimeMinute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

