/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ChronoSheetsClientLibModel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Fields used to save an OrganisationGroup
 */
@ApiModel(description = "Fields used to save an OrganisationGroup")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-03T21:12:18.282+10:00[Australia/Sydney]")
public class SaveOrganisationGroupRequest {
  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_ORGANISATION_GROUP_NAME = "OrganisationGroupName";
  @SerializedName(SERIALIZED_NAME_ORGANISATION_GROUP_NAME)
  private String organisationGroupName;

  public static final String SERIALIZED_NAME_IS_DELETED = "IsDeleted";
  @SerializedName(SERIALIZED_NAME_IS_DELETED)
  private Boolean isDeleted;


  public SaveOrganisationGroupRequest id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The Id of the Organisation Group you want to update/save
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Id of the Organisation Group you want to update/save")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public SaveOrganisationGroupRequest organisationGroupName(String organisationGroupName) {
    
    this.organisationGroupName = organisationGroupName;
    return this;
  }

   /**
   * The updated name of the Organisation Group
   * @return organisationGroupName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The updated name of the Organisation Group")

  public String getOrganisationGroupName() {
    return organisationGroupName;
  }


  public void setOrganisationGroupName(String organisationGroupName) {
    this.organisationGroupName = organisationGroupName;
  }


  public SaveOrganisationGroupRequest isDeleted(Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Whether or not the Organisation Group is to be marked as deleted
   * @return isDeleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not the Organisation Group is to be marked as deleted")

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveOrganisationGroupRequest saveOrganisationGroupRequest = (SaveOrganisationGroupRequest) o;
    return Objects.equals(this.id, saveOrganisationGroupRequest.id) &&
        Objects.equals(this.organisationGroupName, saveOrganisationGroupRequest.organisationGroupName) &&
        Objects.equals(this.isDeleted, saveOrganisationGroupRequest.isDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, organisationGroupName, isDeleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveOrganisationGroupRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    organisationGroupName: ").append(toIndentedString(organisationGroupName)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

